"""Initial migration

Revision ID: 5209e6303a30
Revises: 
Create Date: 2024-02-22 00:49:26.848805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5209e6303a30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('SurnameName', sa.String(), nullable=False),
    sa.Column('HashedPassword', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('Email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
