"""Add unique values

Revision ID: f8708170a4ca
Revises: e8180dc4340d
Create Date: 2024-02-23 01:25:09.509754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8708170a4ca'
down_revision: Union[str, None] = 'e8180dc4340d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ClassesInfo', ['ClassId'])
    op.create_unique_constraint(None, 'LessonsInfo', ['LessonId'])
    op.create_unique_constraint(None, 'ModulesInfo', ['ModuleId'])
    op.create_unique_constraint(None, 'Steps', ['StepId'])
    op.create_unique_constraint(None, 'Users', ['Email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_constraint(None, 'Steps', type_='unique')
    op.drop_constraint(None, 'ModulesInfo', type_='unique')
    op.drop_constraint(None, 'LessonsInfo', type_='unique')
    op.drop_constraint(None, 'ClassesInfo', type_='unique')
    # ### end Alembic commands ###
