version: "3"

services:
  ManuScriptDB:
    image: "postgres:15"
    environment:
      - "POSTGRES_DB=ManuScriptDB"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"